build:
    environment:
        php: "7.4"
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
filter:
    excluded_paths:
        - 'l10n/*'
        - 'tests/'
        - 'vendor/*'
imports:
    - php
tools:
    external_code_coverage: true